pipeline {
    agent {
        docker{
            image 'node:18'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                // Get source code from a GitHub repository
                git branch:'master', url:'https://github.com/Tzu-Lun/devops-task-room.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir("./client/") {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir("./client/") {
                   sh 'npm run build'
                }
            }
        }
        stage('Deploy to AWS S3 bucket') {
            steps {
              withAWS(credentials: 'aws-p3l1-jenkins-credential', region: 'ap-southeast-2'){
                  sh 'aws s3 ls'
                  sh 'aws s3 cp build s3://p3l1devops'
                  sh 'aws s3 cp index.html s3://p3l1devops'
                }
            }
        }
    }
}                   
    post {
        always {
            cleanWs() // Clean up workspace
        }
    }
    