pipeline {
    agent {
        docker {
        image 'node:18.0.0'
        args '-u root:root'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                // Get source code from a GitHub repository
                git branch:'master', url:'https://github.com/Tzu-Lun/devops-task-room.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir("./client/") {
                    sh 'node --version'
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir("./client/") {
                   sh 'npm run build'
                }
            }
        }
        stage('Deploy to AWS S3 bucket') {
            steps {
               withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'p3l1-jenkins-aws-credential-s3', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                  sh 'aws s3 ls'
                  sh 'aws s3 cp build s3://p3l1devops'
                  sh 'aws s3 cp index.html s3://p3l1devops'
                }
            }
        }
    }
}                   