pipeline {
    agent any

     environment {
        NODEJS_HOME = tool name: 'NodeJS', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
        PATH = "${env.NODEJS_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                // Get source code from a GitHub repository
                git branch:'master', url:'https://github.com/Tzu-Lun/devops-task-room.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir("./client/") {
                    sh 'npm install'
                }
            }
        }
        
        stage('Build') {
            steps {
                dir("./client/") {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Deploy to AWS S3 bucket') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-p3l1-jenkins-credential', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                      sh 'aws s3 ls'
                      sh 'aws s3 sync client/builds3://p3l1devops/'
                    }
                }
            }
        }
    }
}          